flowchart TD
    5thEdition\[5th Edition\] ---> \[6thEdition6th Edition]
    5thEdition\[5th Edition\] ---> \[PWB1.0PWB 1.0]
    6thEdition\[6th Edition\] ---> \[LSXLSX]
    6thEdition\[6th Edition\] ---> \[1BSD1 BSD]
    6thEdition\[6th Edition\] ---> \[MiniUnixMini Unix]
    6thEdition\[6th Edition\] ---> \[WollongongWollongong]
    6thEdition\[6th Edition\] ---> \[InterdataInterdata]
    PWB1.0\[PWB 1.0\] ---> \[PWB1.2PWB 1.2]
    PWB1.0\[PWB 1.0\] ---> \[USG1.0USG 1.0]
    1BSD\[1 BSD\] ---> \[2BSD2 BSD]
    Interdata\[Interdata\] ---> \[Unix/TS3.0Unix/TS 3.0]
    Interdata\[Interdata\] ---> \[PWB2.0PWB 2.0]
    Interdata\[Interdata\] ---> \[7thEdition7th Edition]
    Unix/TS3.0\[Unix/TS 3.0\] ---> \[TS4.0TS 4.0]
    PWB2.0\[PWB 2.0\] ---> \[Unix/TS3.0Unix/TS 3.0]
    7thEdition\[7th Edition\] ---> \[8thEdition8th Edition]
    7thEdition\[7th Edition\] ---> \[32V32V]
    7thEdition\[7th Edition\] ---> \[V7MV7M]
    7thEdition\[7th Edition\] ---> \[Ultrix-11Ultrix-11]
    7thEdition\[7th Edition\] ---> \[XenixXenix]
    7thEdition\[7th Edition\] ---> \[UniPlus+UniPlus+]
    8thEdition\[8th Edition\] ---> \[9thEdition9th Edition]
    32V\[32V\] ---> \[3BSD3 BSD]
    V7M\[V7M\] ---> \[Ultrix-11Ultrix-11]
    2BSD\[2 BSD\] ---> \[2.8BSD2.8 BSD]
    2.8BSD\[2.8 BSD\] ---> \[Ultrix-11Ultrix-11]
    2.8BSD\[2.8 BSD\] ---> \[2.9BSD2.9 BSD]
    3BSD\[3 BSD\] ---> \[4BSD4 BSD]
    4BSD\[4 BSD\] ---> \[4.1BSD4.1 BSD]
    4.1BSD\[4.1 BSD\] ---> \[4.2BSD4.2 BSD]
    4.1BSD\[4.1 BSD\] ---> \[2.8BSD2.8 BSD]
    4.1BSD\[4.1 BSD\] ---> \[8thEdition8th Edition]
    4.2BSD\[4.2 BSD\] ---> \[4.3BSD4.3 BSD]
    4.2BSD\[4.2 BSD\] ---> \[Ultrix-32Ultrix-32]
    PWB1.2\[PWB 1.2\] ---> \[PWB2.0PWB 2.0]
    USG1.0\[USG 1.0\] ---> \[CBUnix1CB Unix 1]
    USG1.0\[USG 1.0\] ---> \[USG2.0USG 2.0]
    CBUnix1\[CB Unix 1\] ---> \[CBUnix2CB Unix 2]
    USG2.0\[USG 2.0\] ---> \[USG3.0USG 3.0]
    CBUnix2\[CB Unix 2\] ---> \[CBUnix3CB Unix 3]
    CBUnix3\[CB Unix 3\] ---> \[Unix/TS++Unix/TS++]
    CBUnix3\[CB Unix 3\] ---> \[PDP-11SysVPDP-11 Sys V]
    CBUnix3\[CB Unix 3\] ---> \[TS4.0TS 4.0]
    Unix/TS++\[Unix/TS++\] ---> \[TS4.0TS 4.0]
    USG3.0\[USG 3.0\] ---> \[Unix/TS3.0Unix/TS 3.0]
    Unix/TS1.0\[Unix/TS 1.0\] ---> \[Unix/TS3.0Unix/TS 3.0]
    TS4.0\[TS 4.0\] ---> \[SystemV.0System V.0]
    SystemV.0\[System V.0\] ---> \[SystemV.2System V.2]
    SystemV.2\[System V.2\] ---> \[SystemV.3System V.3]
