flowchart TD
    a[a] ---> b[b]
    a[a] ---> c[c]
    b[b] ---> a[a]
    b[b] ---> d[d]
    b[b] ---> e[e]
    d[d] ---> b[b]
    d[d] ---> g[g]
    g[g] ---> d[d]
    e[e] ---> b[b]
    c[c] ---> a[a]
    c[c] ---> f[f]
    f[f] ---> c[c]
