flowchart TD
    layers[layers] ---> usr[usr]
    Linux kernel diagram["Linux kernel diagram"] ---> multitasking[multitasking]
    CPU[CPU] ---> © 2007 Constantine Shulyupin https://makelinux.github.io/kernel/diagram["© 2007 Constantine Shulyupin https://makelinux.github.io/kernel/diagram"]
    functions[functions] ---> layers[layers]
    usr[usr] ---> usr_[usr_]
    usr[usr] ---> virt[virt]
    virt[virt] ---> D0[D0]
    virt[virt] ---> bridges[bridges]
    bridges[bridges] ---> E0[E0]
    bridges[bridges] ---> logical[logical]
    logical[logical] ---> F0[F0]
    logical[logical] ---> HWI[HWI]
    HWI[HWI] ---> G0[G0]
    HWI[HWI] ---> HW[HW]
    HW[HW] ---> H0[H0]
