flowchart TD
    [""] ---> x1[x1]
    [""] ---> x2[x2]
    [""] ---> x3[x3]
    [""] ---> x4[x4]
    [""] ---> x5[x5]
    [""] ---> x6[x6]
    [""] ---> x7[x7]
    [""] ---> x8[x8]
    [""] ---> x9[x9]
    vis[vis] ---> x1[x1]
    vis[vis] ---> x2[x2]
    vis[vis] ---> x3[x3]
    vis[vis] ---> math[math]
    vis[vis] ---> text[text]
    text[text] ---> x4[x4]
    text[text] ---> x5[x5]
    text[text] ---> x6[x6]
    text[text] ---> math[math]
    math[math] ---> x7[x7]
    math[math] ---> x8[x8]
    math[math] ---> x9[x9]
