flowchart TD
    e[e] ---> clusterB[clusterB]
    d[d] ---> D[D]
    D[D] ---> d[d]
    clusterB[clusterB] ---> e[e]
    clusterB[clusterB] ---> clusterC[clusterC]
    clusterC[clusterC] ---> clusterB[clusterB]
