flowchart TD
    fingerprint:ubid_out:e[fingerprint":"ubid_out":e] ---> pubkey:ubid_in:_[pubkey":"ubid_in":_]
    issuer:ubid_out:e[issuer":"ubid_out":e] ---> pubkey:ubid_in:_[pubkey":"ubid_in":_]
    userid:ubid_out:e[userid":"ubid_out":e] ---> pubkey:ubid_in:_[pubkey":"ubid_in":_]
