flowchart TD
    user[user] ---> app[app]
    app[app] ---> provider-backend[provider-backend]
    provider-backend[provider-backend] ---> public-api[public-api]
    public-api[public-api] ---> state-service[state-service]
    public-api[public-api] ---> resource-service[resource-service]
    state-service[state-service] ---> DynamoDB[DynamoDB]
    resource-service[resource-service] ---> RDS[RDS]
    customer-service[customer-service] ---> admin-gui[admin-gui]
    customer-service[customer-service] ---> provider-developer[provider-developer]
    admin-gui[admin-gui] ---> admin-api[admin-api]
    admin-api[admin-api] ---> resource-service[resource-service]
    IOT Gateway[IOT Gateway] ---> Kinesis[Kinesis]
    Kinesis[Kinesis] ---> DynamoDB[DynamoDB]
    thing[thing] ---> IOT Gateway[IOT Gateway]
